// types.js

export const FETCH_SITES = 'FETCH_SITES';
export const RECEIVED_SITES = 'RECEIVED_SITES';
export const SITE_SELECTED = 'SITE_SELECTED';
export const FETCH_MEASUREMENTS = 'FETCH_MEASUREMENTS';
export const RECEIVED_MEASUREMENTS = 'RECEIVED_MEASUREMENTS';
export const FETCH_TRAFFIC = 'FETCH_TRAFFIC';
export const RECEIVED_TRAFFIC = 'RECEIVED_TRAFFIC';
export const FETCH_FIRES = 'FETCH_FIRES';
export const RECEIVED_FIRES = 'RECEIVED_FIRES';
export const FIRE_SELECTED = 'FIRE_SELECTED';
