// types.js

export const FETCH_SITES = 'FETCH_SITES';
export const RECEIVED_SITES = 'RECEIVED_SITES';
export const SITE_SELECTED = 'SITE_SELECTED';

export const FETCH_MEASUREMENTS = 'FETCH_MEASUREMENTS';
export const RECEIVED_MEASUREMENTS = 'RECEIVED_MEASUREMENTS';

export const FETCH_VICROADS_TRAFFIC = 'FETCH_VICROADS_TRAFFIC';
export const RECEIVED_VICROADS_TRAFFIC = 'RECEIVED_VICROADS_TRAFFIC';
export const FETCH_BING_TRAFFIC = 'FETCH_BING_TRAFFIC';
export const RECEIVED_BING_TRAFFIC = 'RECEIVED_BING_TRAFFIC';

export const FETCH_FIRES = 'FETCH_FIRES';
export const RECEIVED_FIRES = 'RECEIVED_FIRES';
export const FIRE_SELECTED = 'FIRE_SELECTED';
export const FIRES_FAILURE = 'FIRES_FAILURE';

export const FETCH_HISTORIC_FIRES = 'FETCH_HISTORIC_FIRES';
export const RECEIVED_HISTORIC_FIRES = 'RECEIVED_HISTORIC_FIRES';
export const HISTORIC_FIRE_SELECTED = 'HISTORIC_FIRE_SELECTED';
export const HISTORIC_FIRES_FAILURE = 'HISTORIC_FIRES_FAILURE';

export const FETCH_AQI_SCALES = 'FETCH_AQI_SCALES';
export const RECEIVED_AQI_SCALES = 'RECEIVED_AQI_SCALES';
export const AQI_SCALE_SELECTED = 'AQI_SCALE_SELECTED';

export const RECEIVED_AQI_FORECASTS = 'RECEIVED_AQI_FORECASTS';
export const FETCH_AQI_FORECASTS = 'FETCH_AQI_FORECASTS';
export const EXPERIMENTS_MAP_REQUEST = 'EXPERIMENTS_MAP_REQUEST';
export const EXPERIMENTS_MAP_SUCCESS = 'EXPERIMENTS_MAP_SUCCESS';
export const EXPERIMENTS_MAP_FAILURE = 'EXPERIMENTS_MAP_FAILURE';
export const EXPERIMENTS_DATE_SELECTED = 'EXPERIMENTS_DATE_SELECTED';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const LOGOUT = 'USERS_LOGOUT';

export const GETME_REQUEST = 'USERS_GETME_REQUEST';
export const GETME_SUCCESS = 'USERS_GETME_SUCCESS';
export const GETME_FAILURE = 'USERS_GETME_FAILURE';

export const DELETE_REQUEST = 'USERS_DELETE_REQUEST';
export const DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const DELETE_FAILURE = 'USERS_DELETE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const GET_QUESTIONNAIRE_REQUEST = 'USERS_GET_QUESTIONNAIRE_REQUEST';
export const GET_QUESTIONNAIRE_SUCCESS = 'USERS_GET_QUESTIONNAIRE_SUCCESS';
export const GET_QUESTIONNAIRE_FAILURE = 'USERS_GET_QUESTIONNAIRE_FAILURE';
